version: '3'
services:
  db:
    image: mysql:8.0.25
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=apiprojectmanagement
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/projects/bancodados/docker/volumes/ApiProjectManagement
      
  apiprojectmanagement:
    build:
      context: ./
      dockerfile: ./Dockerfile
    #image: 296c24aba4b8
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    depends_on:
      - db